apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mysql.initdbConfigMapName }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS {{ .Values.mysql.database }};
    USE {{ .Values.mysql.database }};
    CREATE TABLE messages (id INT AUTO_INCREMENT PRIMARY KEY, message TEXT);
