apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/auth-keepalive-timeout: "1800"

spec:
  ingressClassName: "nginx"  
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: two-tier-app-service
                port:
                  number: 80
          - path: /new
            pathType: Prefix
            backend:
              service:
                name: httpd-service
                port:
                  number: 80



# # helm install nginx-ingress ingress-nginx/ingress-nginx   --version 4.0.6   --namespace nginx-ingress   --create-namespace   --set controller.service.type=LoadBalancer   --set controller.service.annotations."service\.beta\.kubernetes\.io/aws-load-balancer-type"="nlb"   --set controller.admissionWebhooks.enabled=false
