apiVersion: v1
kind: Service
metadata:
  labels:
    managed-by: prometheus-operator
    operated-prometheus: "true"
  name: prom-exposed
  namespace: monitoring
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus
  type: LoadBalancer